exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
  -
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          mass_threshold: 80