exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
  - "**/summaries/"
version: "2"
checks:
    method-lines:
      config:
        threshold: 50
plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          mass_threshold: 80