exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
  - "**/*.md"
  - "**/*.yml"
  - "*.md"
  - "*.yml"
  - "*.xml"
version: "2"
checks:
    method-lines:
      config:
        threshold: 50
    method-count:
      config:
        threshold: 35
plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          mass_threshold: 250
